---
editor_options:
  markdown:
    wrap: 72
---

price - price of the houses in rupees. This is the response variable
(integer) area - area of a house in square feet (integer) bedrooms -
number of bedrooms in house (integer) bathrooms - number of bathrooms in
house (integer) stories - number of stories in house (integer)
mainroad - whether or not house is connected to main road (boolean)
guestroom - whether or not house has a guest room (boolean) basement -
whether or not house has a basement (boolean) hotwaterheating - whether
or not house has a hot-water heater (boolean) airconditioning - whether
or not house has air conditioning (boolean) parking - number of parking
spots at house (integer) prefarea - whether or not the house is in a
preferred area (boolean) furnishingstatus - furnishing status of the
house (string)

| Attribute        | Description                                     | Data Type |
|--|--------------------------------------------------------------------------|--|
| price            | Price of the houses in rupees.                  | Integer   |
| area             | Area of a house in square fee                   | Integer   |
| bedrooms         | Number of bedrooms in house                     | Integer   |
| bathrooms        | Number of bathrooms in house                    | Integer   |
| stories          | Number of stories in house                      | Integer   |
| mainroad         | Whether or not house is connected to main road  | Boolean   |
| guestroom        | Whether or not house has a guest room           | Boolean   |
| basement         | Whether or not house has a basement             | Boolean   |
| hotwaterheating  | Whether or not house has a hot-water heate      | Boolean   |
| airconditioning  | Whether or not house has air conditioning       | Boolean   |
| parking          | Number of parking spots at house                | Integer   |
| prefarea         | Whether or not the house is in a preferred area | Boolean   |
| furnishingstatus | Furnishing status of the house                  | String    |
